#!/bin/sh
set -e

echo current version: $(gobump show -r ./cmd/fluent-agent-chimera)
read -p "input next version: " next_version

gobump set $next_version -w ./cmd/fluent-agent-chimera
ghch -w -N v$next_version

git add cmd/fluent-agent-chimera/version.go CHANGELOG.md
git commit -m "Checking in changes prior to tagging of version v$next_version"
git tag v$next_version
git push && git push --tags
